using Newtonsoft.Json.Linq;

namespace Assfinet.Shared.Entities;

public class Kunde
    {
        public int Id { get; set; }
        public Guid AmsId { get; set; } 
        public DateTime? Bearbeitet { get; set; }
        public bool Dirty { get; set; } 
        public string License { get; set; }
        public DateTime LastSynchronisation { get; private set; }
        public IDictionary<string, JToken> AdditionalData { get; set; } = new Dictionary<string, JToken>();
        public string Adrid { get; set; }
        public DateTime? Aenderung { get; set; }
        public string Aenderungsgrund { get; set; }
        public string Amsidnr { get; set; }
        public string Anrede { get; set; }
        public string Arbeitgeber { get; set; }
        public decimal? AusbildungskostenMonatlich { get; set; }
        public DateTime? AustrittsdatumArbeitgeber { get; set; }
        public string Bank1 { get; set; }
        public string Bank2 { get; set; }
        public string Bearbeiter { get; set; }
        public string BelegteSparten { get; set; }
        public string Beruf { get; set; }
        public string Berufsstatus { get; set; }
        public string Besitzverhaeltnis { get; set; }
        public string Bic1 { get; set; }
        public string Bic2 { get; set; }
        public string Bilanzstichtag { get; set; }
        public string Blz1 { get; set; }
        public string Blz2 { get; set; }
        public string Branche { get; set; }
        public decimal? Bruttojahresmietwert { get; set; }
        public decimal? Bruttojahresumsatz { get; set; }
        public string Bundesland { get; set; }
        public string Debitor { get; set; }
        public DateTime? DsgvoDeleteDate { get; set; }
        public DateTime? DsgvoLockDate { get; set; }
        public bool? DsgvoLocked { get; set; }
        public string DtazvEntgelt { get; set; }
        public bool? Duzen { get; set; }
        public int? Einkommen { get; set; }
        public DateTime? EintrittsdatumArbeitgeber { get; set; }
        public string EloGid { get; set; }
        public string EmailGeschaeftlich { get; set; }
        public string EmailPrivat { get; set; }
        public int? Erloeskonto { get; set; }
        public DateTime? ErlUwg7 { get; set; }
        public decimal? ErwerbsminderungsrenteTeil { get; set; }
        public decimal? ErwerbsminderungsrenteVoll { get; set; }
        public string Familienstand { get; set; }
        public string Fax { get; set; }
        public string Finanzamt { get; set; }
        public decimal? GAgZuschuss { get; set; }
        public decimal? GAgZuschussProz { get; set; }
        public bool? GAvwl { get; set; }
        public bool? GB2b { get; set; }
        public string GBetriebsart { get; set; }
        public int? GBetriebsartId { get; set; }
        public string Geburtsname { get; set; }
        public string Geburtsort { get; set; }
        public DateTime? Geburtstag { get; set; }
        public string Geschlecht { get; set; }
        public decimal? GesetzlicheAltersrenteMonatlich { get; set; }
        public decimal? GesetzlicheBURenteMonatlich { get; set; }
        public decimal? GesetzlicheHinterbliebenenRenteMonatlich { get; set; }
        public bool? GesetzlichKrankenversichert { get; set; }
        public bool? GesetzlichRentenversichert { get; set; }
        public DateTime? GewuenschterRentenbeginn { get; set; }
        public DateTime? Gruendung { get; set; }
        public decimal? GrundstueckM { get; set; }
        public string GTarif1 { get; set; }
        public string GTarif2 { get; set; }
        public string GTarif3 { get; set; }
        public string GTarif4 { get; set; }
        public string GTarif5 { get; set; }
        public DateTime? GueltigAb { get; set; }
        public DateTime? GueltigBis { get; set; }
        public string GVersicherer1 { get; set; }
        public string GVersicherer2 { get; set; }
        public string GVersicherer3 { get; set; }
        public string GVersicherer4 { get; set; }
        public string GVersicherer5 { get; set; }
        public string GVstAbzug { get; set; }
        public decimal? GVstAnteil { get; set; }
        public DateTime? GVstSeit { get; set; }
        public bool? GVtAccount { get; set; }
        public bool? GZuschussAltVt { get; set; }
        public string Handelsregisternummer { get; set; }
        public bool? Hinterbliebenenrente { get; set; }
        public string HistorieZuKunde { get; set; }
        public bool? Honorarkunde { get; set; }
        public string Iban1 { get; set; }
        public string Iban2 { get; set; }
        public DateTime? IdentDate { get; set; }
        public DateTime? IdentGueltigBis { get; set; }
        public string IdentTyp { get; set; }
        public decimal? Inflationsrate { get; set; }
        public string Info_01 { get; set; }
        public string Informationsweg { get; set; }
        public string InhaberGF { get; set; }
        public string InterneNr { get; set; }
        public string Internet { get; set; }
        public bool? IsHistorie { get; set; }
        public string IsoLand { get; set; }
        public bool? IsZukunft { get; set; }
        public decimal? Kapitalmarktzins { get; set; }
        public string KeyIdentDate { get; set; }
        public int? Kinder { get; set; }
        public string Kindergeldnummer { get; set; }
        public decimal? KinderLautSteuerkarte { get; set; }
        public bool? Kirchensteuer { get; set; }
        public string Klasse { get; set; }
        public string Konto1 { get; set; }
        public string Konto2 { get; set; }
        public string Kontobezeichnung1 { get; set; }
        public string Kontobezeichnung2 { get; set; }
        public string Kontoinhaber1 { get; set; }
        public string Kontoinhaber2 { get; set; }
        public decimal? Kundeninkassokonto { get; set; }
        public string Kundenname { get; set; }
        public string KundennamePhonetisch { get; set; }
        public string Kundentyp { get; set; }
        public string Kundenverbindung { get; set; }
        public DateTime? KundeSeit { get; set; }
        public string LageBetriebsgrundstuecks { get; set; }
        public string Land { get; set; }
        public string Landesname { get; set; }
        public DateTime? LetzterBesuch { get; set; }
        public decimal? LohnGehaltssumme { get; set; }
        public DateTime? MahnstopBis { get; set; }
        public DateTime? MaklervertragBis { get; set; }
        public DateTime? MaklervertragDatum { get; set; }
        public string Mandant { get; set; }
        public string MandantAmsidnr { get; set; }
        public decimal? MieteNebenkostenMonatlich { get; set; }
        public decimal? Mietsteigerung { get; set; }
        public int? Mitarbeiterzahl { get; set; }
        public string Mobiltelefon { get; set; }
        public string Name { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public decimal? NichtSelbstaendigeArbeitBruttoMonatlich { get; set; }
        public decimal? NichtSelbstaendigeArbeitBruttoJaehrlich { get; set; }
        public decimal? Nettojahresmietwert { get; set; }
        public string Nummer { get; set; }
        public string Objektnummer { get; set; }
        public string OffenbarungspflichtZurZahlung1 { get; set; }
        public string OffenbarungspflichtZurZahlung2 { get; set; }
        public string OffenbarungspflichtZurZahlung3 { get; set; }
        public string OffenbarungspflichtZurZahlung4 { get; set; }
        public string OffenbarungspflichtZurZahlung5 { get; set; }
        public string OffenbarungspflichtZurZahlung6 { get; set; }
        public decimal? OffenePosten { get; set; }
        public string OffenePostenErlass { get; set; }
        public DateTime? OffenePostenErloes { get; set; }
        public decimal? OffenePostenSumme { get; set; }
        public string Ort { get; set; }
        public string OrtLand { get; set; }
        public string OrtLandName { get; set; }
        public string Personalnummer { get; set; }
        public string Postleitzahl { get; set; }
        public string Praxis { get; set; }
        public string Profession { get; set; }
        public DateTime? Rentenbeginn { get; set; }
        public decimal? Rente { get; set; }
        public bool? RenteBezueger { get; set; }
        public decimal? RenteJaehrlich { get; set; }
        public bool? Rentenversicherung { get; set; }
        public string Risikolebensversicherung { get; set; }
        public string Sposialversicherung { get; set; }
        public string Status { get; set; }
        public string Steuernummer { get; set; }
        public string SteuerpflichtigerKonto { get; set; }
        public string SteuernummerFestsetzung { get; set; }
        public string Telefon { get; set; }
        public string Titel { get; set; }
        public DateTime? Unterschriftsdatum { get; set; }
        public string UszId { get; set; }
        public decimal? UStSatz { get; set; }
        public decimal? UStVorschuss { get; set; }
        public string Versicherungsnummer { get; set; }
        public string Vorsorgekasse { get; set; }
        public bool? WaehrungCHF { get; set; }
        public string WaehrungEUR { get; set; }
        public decimal? Warenbestand { get; set; }
        public string Website { get; set; }
        public string Wohnort { get; set; }
        public string WohnortLand { get; set; }
        public string WohnortLandName { get; set; }
    }