namespace Assfinet.Shared.Models
{
    public class UnfModel : VertragSparteModel
    {
        public string UNF101 { get; set; }
        public string UNF102 { get; set; }
        public string UNF104 { get; set; }
        public string UNF105 { get; set; }
        public string UNF106 { get; set; }
        public string UNF107 { get; set; }
        public string UNF108 { get; set; }
        public string UNF109 { get; set; }
        public string UNF110 { get; set; }
        public string UNF111 { get; set; }
        public string UNF112 { get; set; }
        public string UNF113 { get; set; }
        public string UNF114 { get; set; }
        public string UNF115 { get; set; }
        public string UNF116 { get; set; }
        public string UNF117 { get; set; }
        public string UNF118 { get; set; }
        public string UNF119 { get; set; }
        public string UNF120 { get; set; }
        public string UNF125 { get; set; }
        public string UNF126 { get; set; }
        public string UNF127 { get; set; }
        public string UNF128 { get; set; }
        public string UNF129 { get; set; }
        public string UNF130 { get; set; }
        public string UNF134 { get; set; }
        public string UNF135 { get; set; }
        public string UNF136 { get; set; }
        public string UNF137 { get; set; }
        public string UNF138 { get; set; }
        public string UNF139 { get; set; }
        public string UNF140 { get; set; }
        public string UNF141 { get; set; }
        public string UNF142 { get; set; }
        public string UNF143 { get; set; }
        public string UNF144 { get; set; }
        public string UNF145 { get; set; }
        public string UNF146 { get; set; }
        public string UNF147 { get; set; }
        public string UNF148 { get; set; }
        public string UNF149 { get; set; }
        public string UNF150 { get; set; }
        public string UNF151 { get; set; }
        public string UNF152 { get; set; }
        public string UNF153 { get; set; }
        public string UNF154 { get; set; }
        public string UNF155 { get; set; }
        public string UNF156 { get; set; }
        public string UNF157 { get; set; }
        public string UNF158 { get; set; }
        public string UNF160 { get; set; }
        public string UNF161 { get; set; }
        public string UNF162 { get; set; }
        public string UNF163 { get; set; }
        public string UNF172 { get; set; }
        public string UNF173 { get; set; }
        public string UNF174 { get; set; }
        public string UNF175 { get; set; }
        public string UNF176 { get; set; }
        public string UNF177 { get; set; }
        public string UNF192 { get; set; }
        public string UNF193 { get; set; }
        public string UNF194 { get; set; }
        public string UNF195 { get; set; }
        public string UNF196 { get; set; }
        public string UNF197 { get; set; }
        public string UNF198 { get; set; }
        public string UNF199 { get; set; }
        public string UNF204 { get; set; }
        public string UNF205 { get; set; }
        public string UNF206 { get; set; }
        public string UNF207 { get; set; }
        public string UNF208 { get; set; }
        public string UNF211 { get; set; }
        public string UNF212 { get; set; }
        public string UNF213 { get; set; }
        public string UNF214 { get; set; }
        public string UNF215 { get; set; }
        public string UNF216 { get; set; }
        public string UNF217 { get; set; }
        public string UNF218 { get; set; }
        public string UNF219 { get; set; }
        public string UNF220 { get; set; }
        public string UNF221 { get; set; }
        public string UNF222 { get; set; }
        public string UNF223 { get; set; }
        public string UNF224 { get; set; }
        public string UNF225 { get; set; }
        public string UNF226 { get; set; }
        public string UNF227 { get; set; }
        public string UNF228 { get; set; }
        public string UNF229 { get; set; }
        public string UNF230 { get; set; }
        public string UNF231 { get; set; }
        public string UNF232 { get; set; }
        public string UNF233 { get; set; }
        public string UNF234 { get; set; }
        public string UNF235 { get; set; }
        public string UNF236 { get; set; }
        public string UNF237 { get; set; }
        public string UNF238 { get; set; }
        public string UNF239 { get; set; }
        public string UNF240 { get; set; }
        public string UNF241 { get; set; }
        public string UNF242 { get; set; }
        public string UNF243 { get; set; }
        public string UNF244 { get; set; }
        public string UNF245 { get; set; }
        public string UNF265 { get; set; }
        public string UNF266 { get; set; }
        public string UNF267 { get; set; }
        public string UNF268 { get; set; }
        public string UNF269 { get; set; }
        public string UNF270 { get; set; }
        public string UNF271 { get; set; }
        public string UNF272 { get; set; }
        public string UNF273 { get; set; }
        public string UNF274 { get; set; }
        public string UNF275 { get; set; }
        public string UNF276 { get; set; }
        public string UNF277 { get; set; }
        public string UNF278 { get; set; }
        public string UNF279 { get; set; }
        public string UNF280 { get; set; }
        public string UNF281 { get; set; }
        public string UNF282 { get; set; }
        public string UNF283 { get; set; }
        public string UNF284 { get; set; }
        public string UNF285 { get; set; }
        public string UNF286 { get; set; }
        public string UNF287 { get; set; }
        public string UNF288 { get; set; }
        public string UNF289 { get; set; }
        public string UNF290 { get; set; }
        public string UNF291 { get; set; }
        public string UNF292 { get; set; }
        public string UNF293 { get; set; }
        public string UNF294 { get; set; }
        public string UNF295 { get; set; }
        public string UNF296 { get; set; }
        public string UNF297 { get; set; }
        public string UNF298 { get; set; }
        public string UNF299 { get; set; }
        public string UNF300 { get; set; }
        public string UNF301 { get; set; }
        public string UNF302 { get; set; }
        public string UNF303 { get; set; }
        public string UNF304 { get; set; }
        public string UNF305 { get; set; }
        public string UNF306 { get; set; }
        public string UNF307 { get; set; }
        public string UNF308 { get; set; }
        public string UNF309 { get; set; }
        public string UNF310 { get; set; }
        public string UNF311 { get; set; }
        public string UNF312 { get; set; }
        public string UNF313 { get; set; }
        public string UNF314 { get; set; }
        public string UNF315 { get; set; }
        public string UNF316 { get; set; }
        public string UNF317 { get; set; }
        public string UNF318 { get; set; }
        public string UNF319 { get; set; }
        public string UNF320 { get; set; }
        public string UNF321 { get; set; }
        public string UNF322 { get; set; }
        public string UNF323 { get; set; }
        public string UNF326 { get; set; }
        public string UNF327 { get; set; }
        public string UNF328 { get; set; }
        public string UNF329 { get; set; }
        public string UNF330 { get; set; }
        public string UNF331 { get; set; }
        public string UNF332 { get; set; }
        public string UNF333 { get; set; }
        public string UNF334 { get; set; }
        public string UNF335 { get; set; }
        public string UNF336 { get; set; }
        public string UNF337 { get; set; }
        public string UNF338 { get; set; }
        public string UNF339 { get; set; }
        public string UNF340 { get; set; }
        public string UNF341 { get; set; }
        public string UNF342 { get; set; }
        public string UNF343 { get; set; }
        public string UNF344 { get; set; }
        public string UNF345 { get; set; }
        public string UNF401 { get; set; }
        public string UNF402 { get; set; }
        public string UNF403 { get; set; }
        public string UNF404 { get; set; }
        public string UNF405 { get; set; }
        public string UNF406 { get; set; }
        public string UNF407 { get; set; }
        public string UNF408 { get; set; }
        public string UNF409 { get; set; }
        public string UNF410 { get; set; }
        public string UNF411 { get; set; }
        public string UNF412 { get; set; }
        public string UNF413 { get; set; }
        public string UNF414 { get; set; }
        public string UNF415 { get; set; }
        public string UNF416 { get; set; }
        public string UNF417 { get; set; }
        public string UNF418 { get; set; }
        public string UNF419 { get; set; }
        public string UNF420 { get; set; }
        public string UNF421 { get; set; }
        public string UNF422 { get; set; }
        public string UNF423 { get; set; }
        public string UNF424 { get; set; }
        public string UNF425 { get; set; }
        public string UNF426 { get; set; }
        public string UNF427 { get; set; }
        public string UNF428 { get; set; }
        public string UNF429 { get; set; }
        public string UNF430 { get; set; }
        public string UNF431 { get; set; }
        public string UNF432 { get; set; }
        public string UNF433 { get; set; }
        public string UNF434 { get; set; }
        public string UNF435 { get; set; }
        public string UNF436 { get; set; }
        public string UNF437 { get; set; }
        public string UNF438 { get; set; }
        public string UNF439 { get; set; }
        public string UNF440 { get; set; }
        public string UNF441 { get; set; }
        public string UNF442 { get; set; }
        public string UNF443 { get; set; }
        public string UNF444 { get; set; }
        public string UNF445 { get; set; }
        public string UNF446 { get; set; }
        public string UNF447 { get; set; }
        public string UNF448 { get; set; }
        public string UNF449 { get; set; }
        public string UNF450 { get; set; }
        public string UNF451 { get; set; }
        public string UNF452 { get; set; }
        public string UNF453 { get; set; }
        public string UNF454 { get; set; }
        public string UNF455 { get; set; }
        public string UNF456 { get; set; }
        public string UNF457 { get; set; }
        public string UNF458 { get; set; }
        public string UNF459 { get; set; }
        public string UNF460 { get; set; }
        public string UNF462 { get; set; }
        public string UNF463 { get; set; }
        public string UNF464 { get; set; }
        public string UNF465 { get; set; }
        public string UNF466 { get; set; }
        public string UNF486 { get; set; }
        public string UNF487 { get; set; }
        public string UNF488 { get; set; }
        public string UNF489 { get; set; }
        public string UNF490 { get; set; }
        public string UNF491 { get; set; }
        public string UNF492 { get; set; }
        public string UNF493 { get; set; }
        public string UNF494 { get; set; }
        public string UNF495 { get; set; }
        public string UNF496 { get; set; }
        public string UNF497 { get; set; }
        public string UNF498 { get; set; }
        public string UNF499 { get; set; }
        public string UNF500 { get; set; }
        public string UNF501 { get; set; }
        public string UNF502 { get; set; }
        public string UNF503 { get; set; }
        public string UNF504 { get; set; }
        public string UNF505 { get; set; }
        public string UNF506 { get; set; }
        public string UNF507 { get; set; }
        public string UNF508 { get; set; }
        public string UNF509 { get; set; }
        public string UNF510 { get; set; }
        public string UNF511 { get; set; }
        public string UNF512 { get; set; }
        public string UNF513 { get; set; }
        public string UNF514 { get; set; }
        public string UNF515 { get; set; }
        public string UNF516 { get; set; }
        public string UNF517 { get; set; }
        public string UNF518 { get; set; }
        public string UNF519 { get; set; }
        public string UNF520 { get; set; }
        public string UNF521 { get; set; }
        public string UNF522 { get; set; }
        public string UNF523 { get; set; }
        public string UNF524 { get; set; }
        public string UNF525 { get; set; }
        public string UNF526 { get; set; }
        public string UNF527 { get; set; }
        public string UNF528 { get; set; }
        public string UNF529 { get; set; }
        public string UNF530 { get; set; }
        public string UNF534 { get; set; }
        public string UNF535 { get; set; }
        public string UNF536 { get; set; }
        public string UNF537 { get; set; }
        public string UNF538 { get; set; }
        public string UNF539 { get; set; }
        public string UNF540 { get; set; }
        public string UNF541 { get; set; }
        public string UNF542 { get; set; }
        public string UNF543 { get; set; }
        public string UNF567 { get; set; }
        public string UNF568 { get; set; }
        public string UNF569 { get; set; }
        public string UNF570 { get; set; }
        public string UNF571 { get; set; }
        public string UNF572 { get; set; }
        public string UNF573 { get; set; }
        public string UNF574 { get; set; }
        public string UNF575 { get; set; }
        public string UNF576 { get; set; }
        public string UNF577 { get; set; }
        public string UNF579 { get; set; }
        public string UNF580 { get; set; }
        public string UNF581 { get; set; }
        public string UNF582 { get; set; }
        public string UNF583 { get; set; }
        public string UNF584 { get; set; }
        public string UNF585 { get; set; }
        public string UNF586 { get; set; }
        public string UNF587 { get; set; }
        public string UNF588 { get; set; }
        public string UNF589 { get; set; }
        public string UNF590 { get; set; }
        public string UNF591 { get; set; }
        public string UNF592 { get; set; }
        public string UNF593 { get; set; }
        public string UNF594 { get; set; }
        public string UNF595 { get; set; }
        public string UNF596 { get; set; }
        public string UNF597 { get; set; }
        public string UNF598 { get; set; }
        public string UNF599 { get; set; }
        public string UNF600 { get; set; }
        public string UNF601 { get; set; }
        public string UNF602 { get; set; }
        public string UNF603 { get; set; }
        public string UNF604 { get; set; }
        public string UNF605 { get; set; }
        public string UNF606 { get; set; }
        public string UNF607 { get; set; }
        public string UNF608 { get; set; }
        public string UNF609 { get; set; }
        public string UNF610 { get; set; }
        public string UNF611 { get; set; }
        public string UNF6111 { get; set; }
        public string UNF6112 { get; set; }
        public string UNF6113 { get; set; }
        public string UNF6114 { get; set; }
        public string UNF6115 { get; set; }
        public string UNF6116 { get; set; }
        public string UNF6117 { get; set; }
        public string UNF6118 { get; set; }
        public string UNF612 { get; set; }
        public string UNF613 { get; set; }
        public string UNF614 { get; set; }
        public string UNF6148 { get; set; }
        public string UNF615 { get; set; }
        public string UNF6150 { get; set; }
        public string UNF6152 { get; set; }
        public string UNF6156 { get; set; }
        public string UNF616 { get; set; }
        public string UNF6161 { get; set; }
        public string UNF617 { get; set; }
        public string UNF618 { get; set; }
        public string UNF619 { get; set; }
        public string UNF620 { get; set; }
        public string UNF621 { get; set; }
        public string UNF622 { get; set; }
        public string UNF623 { get; set; }
        public string UNF624 { get; set; }
        public string UNF625 { get; set; }
        public string UNF626 { get; set; }
        public string UNF627 { get; set; }
        public string UNF628 { get; set; }
        public string UNF629 { get; set; }
        public string UNF630 { get; set; }
        public string UNF6301 { get; set; }
        public string UNF6302 { get; set; }
        public string UNF6303 { get; set; }
        public string UNF6304 { get; set; }
        public string UNF6305 { get; set; }
        public string UNF6306 { get; set; }
        public string UNF6307 { get; set; }
        public string UNF6308 { get; set; }
        public string UNF6309 { get; set; }
        public string UNF631 { get; set; }
        public string UNF6310 { get; set; }
        public string UNF6311 { get; set; }
        public string UNF6312 { get; set; }
        public string UNF6313 { get; set; }
        public string UNF6314 { get; set; }
        public string UNF6315 { get; set; }
        public string UNF6316 { get; set; }
        public string UNF6317 { get; set; }
        public string UNF6318 { get; set; }
        public string UNF6319 { get; set; }
        public string UNF632 { get; set; }
        public string UNF6320 { get; set; }
        public string UNF6321 { get; set; }
        public string UNF6322 { get; set; }
        public string UNF6323 { get; set; }
        public string UNF633 { get; set; }
        public string UNF640 { get; set; }
        public string UNF641 { get; set; }
        public string UNF642 { get; set; }
        public string UNF643 { get; set; }
        public string UNF644 { get; set; }
        public string UNF6601 { get; set; }
        public string UNF6602 { get; set; }
        public string UNF6603 { get; set; }
        public string UNF6604 { get; set; }
        public string UNF6605 { get; set; }
        public string UNF6606 { get; set; }
        public string UNF6607 { get; set; }
        public string UNF6608 { get; set; }
        public string UNF6609 { get; set; }
        public string UNF6610 { get; set; }
        public string UNF6611 { get; set; }
        public string UNF6612 { get; set; }
        public string UNF6613 { get; set; }
    }
}